# Bu araÃ§ @keyiflerolsun tarafÄ±ndan | @KekikAkademi iÃ§in yazÄ±lmÄ±ÅŸtÄ±r.

name: Domain DeÄŸiÅŸiklik KontrolÃ¼

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 30 * * * *

jobs:
  DomainKontrol:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name : Depo KontrolÃ¼
        uses : actions/checkout@v4

      - name : Python 3.11.8 YÃ¼kle
        uses : actions/setup-python@v5
        with :
          python-version: 3.11.8

      - name : Python SÃ¼rÃ¼mÃ¼nÃ¼ GÃ¶ster
        run  : python -c "import sys; print(sys.version)"

      - name : Gereksinimleri YÃ¼kle
        run  : |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel

      - name : BetiÄŸi Ã‡alÄ±ÅŸtÄ±r
        run  : |
          python TRGoals.py

      - name : DeÄŸiÅŸiklik KontrolÃ¼
        id   : degisiklik_kontrol
        run  : |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name : Depoyu GÃ¼ncelle
        if   : steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run  : |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --author="keyiflerolsun <keyiflerolsun@users.noreply.github.com>" \
            -m "â™»ï¸ Domain DeÄŸiÅŸikliÄŸi" -m "ğŸ’¾ Ã–nceki Â» $GITHUB_SHA"
          git push